import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/Header";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import { Toaster } from "@/components/ui/sonner";
import { Annonces } from "@/components/shared/Annonces";

import { Transition } from "@/components/shared/Transition";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "No Cap",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="fr">
      <SessionProvider session={session}>
        <body className="">
          <div className="fixed top-0 w-full z-50">
            <div className="w-full">
              <Annonces />
            </div>
            <Header />
          </div>

          <main className="min-h-screen bg-gradient-to-b from-[#020202] via-[#040404] to-second z-50">
            {children}
          </main>

          <Toaster />
        </body>
      </SessionProvider>
    </html>
  );
}
